---
- name: Test playbook
  hosts: all
  become: true
  tasks: 
   - name: copy a new file
     copy: 
       src: /home/ansadmin/index.html
       dest: /home/ansadmin
       mode: 0600
       owner: Bharat 
