---
- name: my test playbook
  hosts: webservers
  become: true
  tasks: 
  - name: installing httpd
    yum: 
      name: httpd
      state: installed
    notify: start httpd

  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
