---
- name: my test playbook
  hosts: webservers
  become: true
  tasks:
  - name: Multiple module run
    yum:
      name: httpd
      state: installed

  - name: Start httpd service
    service:
     name: httpd
     state: started   
