---
- name: My test playbook
  hosts: webservers
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: install apache2
    yum:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index.html
    copy: 
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0777
