---
- name: my test playbook
  hosts: webservers
  become: true
  tasks: 
  - name: Stopping service
    service:
      name: httpd
      state: stopped

  - name: removing httpd
    yum:
      name: httpd
      state: removed
   

